query GetOrderById($id: Int!){
  orders(where: {id : {eq: $id}} ) {
    id,
    customerId,
    customer {
      firstName,
      lastName
    },
    status,
    orderDate,
    otherNotes,
    descriptions,
    isDelivery,
    totalAmount,
    depositAmount,
    isDelivery
  } 
}